basePath: /api/v1/restaurant
definitions:
  model.Base:
    properties:
      crt_at:
        type: string
      upd_at:
        type: string
    type: object
  model.Customer:
    properties:
      base:
        $ref: '#/definitions/model.Base'
      customer_address:
        type: string
      customer_dob:
        type: string
      customer_email:
        type: string
      customer_id:
        type: string
      customer_name:
        type: string
      customer_phone:
        type: string
      is_deleted:
        type: boolean
    type: object
host: localhost:8081
info:
  contact:
    name: Developer
  description: This page is API documentation for all services relating common data
    or operation.
  title: Web Order API
  version: "1.0"
paths:
  /user/customer:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: customer
        in: body
        name: Data
        required: true
        schema:
          $ref: '#/definitions/model.Customer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
